name: fpga-tool-perf-env
channels:
  - defaults
  - symbiflow
dependencies:
  - symbiflow-yosys=0.8_3925_g6bccd35a=20200627_023447
  - symbiflow-yosys-plugins=1.0.0.7_0041_g1c495fd=20200627_023447
  - symbiflow-vtr=8.0.0.rc2_4003_g8980e4621=20200627_023447
  - nextpnr-xilinx
  - nextpnr-ice40
  - prjxray-tools
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:requirements.txt
