name: fpga-tool-perf-env
channels:
  - m-labs
  - conda-forge
  - pkgw-forge
  - symbiflow
dependencies:
  - yosys
  - yosys-plugins
  - vtr=8.0.0.rc2_3864_g0ece2d2c1
  - nextpnr-xilinx
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:requirements.txt
