name: fpga-tool-perf-env
channels:
  - defaults
  - symbiflow
dependencies:
  - symbiflow-yosys=0.8_3925_g6bccd35a
  - symbiflow-yosys-plugins=1.0.0.7_0032_g104f4fc
  - symbiflow-vtr=8.0.0.rc2_4003_g8980e4621
  - nextpnr-xilinx
  - nextpnr-ice40
  - prjxray-tools
  - prjxray-db
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:requirements.txt
